In [1]:
import numpy as np
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

In [2]:
start_date = '1950-01-01'

In [3]:
multpl_df = pd.read_pickle("../data/20260216_multpl_datasets_snapshot.pickle")
fred_df = pd.read_pickle("../data/20260216_fred_api_datasets_snapshot.pickle")

In [4]:
multpl_df

,book,dividend,div_growth,div_yield,earn,earn_yld,earn_growth,real_earn_growth,sp500_pe,sp500,...,real_gdp_growth,real_gdp_per_cap,us_home_prices,us_avg_income,us_med_income,us_med_income_growth,us_med_real_income,us_infl,us_pop,us_pop_growth
date,,,,,,,,,,,,,,,,,,,,,
1871-03-31,NaN,6.47,NaN,0.0564,9.95,0.0868,NaN,NaN,11.52,4.61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1871-06-30,NaN,6.97,NaN,0.0539,10.73,0.0830,NaN,NaN,12.05,4.82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1871-09-30,NaN,6.92,NaN,0.0537,10.64,0.0826,NaN,NaN,12.10,4.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1871-12-31,NaN,6.66,NaN,0.0549,10.25,0.0844,NaN,NaN,11.85,4.74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1872-03-31,NaN,6.81,NaN,0.0536,10.28,0.0809,NaN,NaN,12.37,5.04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.0146,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-31,1197.11,77.16,0.0751,0.0134,219.57,0.0381,0.1322,0.1058,26.23,5683.98,...,0.0202,68972.63,NaN,NaN,NaN,NaN,NaN,0.0239,341.41,0.0071
2025-06-30,1238.93,77.71,0.0746,0.0128,223.56,0.0369,0.1358,0.1062,27.10,6029.95,...,0.0208,69532.35,NaN,NaN,NaN,NaN,NaN,0.0267,341.87,0.0060
2025-09-30,1270.32,78.30,0.0692,0.0119,233.52,0.0355,0.1687,0.1345,28.13,6584.02,...,0.0234,70170.52,NaN,NaN,NaN,NaN,NaN,0.0301,342.41,0.0056
2025-12-31,NaN,78.92,0.0546,0.0115,NaN,NaN,NaN,NaN,NaN,6853.03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0268,342.91,0.0056
2026-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6872.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
fred_df

,fred_gdp,fred_gnp,fred_baa,fred_aaa,fred_cpi,fred_gs10,fred_tb3ms
1919-03-31,NaN,NaN,7.15,5.39,NaN,NaN,NaN
1919-06-30,NaN,NaN,7.04,5.40,NaN,NaN,NaN
1919-09-30,NaN,NaN,7.27,5.60,NaN,NaN,NaN
1919-12-31,NaN,NaN,7.77,5.73,NaN,NaN,NaN
1920-03-31,NaN,NaN,7.97,5.92,NaN,NaN,NaN
...,...,...,...,...,...,...,...
2025-03-31,29825.182,29864.292,5.93,5.29,319.785,4.28,4.20
2025-06-30,30042.113,30044.191,6.15,5.46,321.435,4.38,4.23
2025-09-30,30485.729,30467.351,5.83,5.21,324.245,4.12,3.92
2025-12-31,NaN,NaN,5.90,5.31,326.031,4.14,3.59
2026-03-31,NaN,NaN,5.88,5.34,326.588,4.21,3.57

In [ ]:
grok_quarter_labels = [

# add contents here
    
]

In [ ]:
# df = pd.concat([price_series, div_series, gdp, gnp, baa, aaa, cpi, gs10, tb3ms], axis=1)
# df.columns = ["price","div","gdp","gnp","baa","aaa","cpi","gs10","tb3ms"]
# df = pd.concat([price_series, div_series, pe_series, book_series, gdp, gnp, baa, aaa, cpi, gs10, tb3ms], axis=1)
# df.columns = ["price","div","pe","book","gdp","gnp","baa","aaa","cpi","gs10","tb3ms"]
# df.index = df.index.strftime('%Y-%m-%d')

quarterly_df = pd.concat([multpl_df, fred_df], axis=1)

quarterly_df = quarterly_df.loc[start_date:] #.dropna()

In [ ]:
quarterly_df

In [ ]:
quarterly_df.columns

In [ ]:
# df["div_yield"] = df["div"] / df["price"]
# df["price_div"] = df["price"] / df["div"]
# df["price_gdp"] = df["price"] / df["gdp"]
# df["price_gnp"] = df["price"] / df["gnp"]
# df["div_minus_baa"] = df["div_yield"] - df["baa"] / 100
# df["credit_spread"] = (df["baa"] - df["aaa"]) / 100
# df["real_price"] = df["price"] / df["cpi"]
# df["real_price_gdp"] = df["real_price"] / df["gdp"]

quarterly_df["div_yield2"] = quarterly_df["dividend"] / quarterly_df["sp500"]
quarterly_df["price_div"] = quarterly_df["sp500"] / quarterly_df["dividend"]
quarterly_df["price_gdp"] = quarterly_df["sp500"] / quarterly_df["gdp"]
quarterly_df["price_gdp2"] = quarterly_df["sp500"] / quarterly_df["fred_gdp"]
quarterly_df["price_gnp2"] = quarterly_df["sp500"] / quarterly_df["fred_gnp"]
quarterly_df["div_minus_baa"] = quarterly_df["div_yield"] - quarterly_df["fred_baa"] / 100.0
quarterly_df["credit_spread"] = (quarterly_df["fred_baa"] - quarterly_df["fred_aaa"]) / 100.0
quarterly_df["real_price2"] = quarterly_df["sp500"] / quarterly_df["cpi"]
quarterly_df["real_price3"] = quarterly_df["sp500"] / quarterly_df["fred_cpi"]
quarterly_df["real_price_gdp2"] = quarterly_df["sp500_adj"] / quarterly_df["gdp"]


# # Calculate ratios (price-based, dividend preferred, anchored to GS10)
# q['div_yield'] = q['div_yield']  # already %
# q['ttm_pe'] = q['pe']
# q['earn_yield'] = 100 / q['ttm_pe']  # earnings yield %
# q['price_book'] = q['close'] / q['book']
# q['credit_spread'] = q['baa'] - q['aaa']
# q['term_spread'] = q['gs10'] - q['tb3ms']
# q['div_premium'] = q['div_yield'] - q['gs10']  # dividend premium over long rate
# q['earn_premium'] = q['earn_yield'] - q['gs10']  # earnings premium over long rate
# q['sp_gdp_proxy'] = q['close'] / q['gdp_lagged']  # simple S&P level to lagged GDP (valuation proxy)

In [ ]:
for col_name in df.columns:
    fig, ax = plt.subplots(figsize=(8, 5))
    date_strings = df.index.values
    dates = [datetime.strptime(str(d), '%Y-%m-%d').date() for d in date_strings]
    values = df[col_name].values
    plt.plot(dates, values, color='blue', linestyle='solid', marker='o') # Plot the data
    formatter = mdates.DateFormatter('%Y-%m-%d')
    ax.xaxis.set_major_formatter(formatter)
    fig.autofmt_xdate()
    plt.title(col_name)
    plt.grid(True)
    plt.show()